#!/usr/bin/env python3
"""Ship only the pop-culture constraints the game actually uses.

js/constraints-pending.js holds 765 candidates and weighs 152 KB. 77 of them are
approved; the other 688 exist for review on /admin/constraints/ and are dead
weight on the three homepages, which are the pages that matter most.

The generated file exposes the same globals under the same names, so no calling
code changes. The admin page keeps loading the full list.

It also removes a determinism hazard. puzzle.js merges repo approvals with a
localStorage staging list, so an admin with staged approvals was getting a
different daily grid from everyone else, on a game whose whole premise is that
the grid is the same worldwide. With only the approved set shipped, a staged id
has nothing to resolve against on the public pages.
"""
import json, pathlib, subprocess, sys

out = subprocess.run(['node', '-e', '''
const fs=require('fs'), vm=require('vm');
const ctx={window:{},console}; vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/constraints-pending.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('js/constraints-approved.js','utf8'),ctx);
const P=ctx.window.PENDING_CONSTRAINTS, A=new Set(ctx.window.APPROVED_PENDING);
// keep the original order: puzzle.js indexes into this pool with a seeded PRNG
const kept=P.filter(c=>A.has(c.id)).map(c=>({id:c.id,en:c.en,fr:c.fr,es:c.es,states:c._states}));
console.log(JSON.stringify({kept, total:P.length, approved:A.size}));
'''], capture_output=True, text=True, check=True)
data = json.loads(out.stdout)
kept = data['kept']
if len(kept) != data['approved']:
    sys.exit(f"approved list has {data['approved']} ids but only {len(kept)} resolved")

lines = [
    '// Generated by scripts/build-live-constraints.py. Do not edit by hand.',
    '//',
    '// The approved pop-culture constraints only. The full 765-candidate list',
    '// lives in constraints-pending.js and is loaded solely by /admin/constraints/.',
    '// Same globals, same order, so puzzle.js indexes into an identical pool.',
    '',
    'const PENDING_CONSTRAINTS = (() => {',
    '  const inS = (str) => { const set = new Set(str.split(/\\s+/).filter(Boolean)); return (s) => set.has(s.id); };',
    '  return [',
]
for c in kept:
    row = json.dumps([c['id'], c['en'], c['fr'], c['es'], c['states']], ensure_ascii=False)
    lines.append(f'    (([id,en,fr,es,st])=>({{id,en,fr,es,match:inS(st),_states:st}}))({row}),')
lines += [
    '  ];',
    '})();',
    '',
    'if (typeof window !== \'undefined\') {',
    '  window.PENDING_CONSTRAINTS = PENDING_CONSTRAINTS;',
    '  window.PENDING_MAP = Object.fromEntries(PENDING_CONSTRAINTS.map(c => [c.id, c]));',
    '}',
    '',
]
p = pathlib.Path('js/constraints-live.js')
p.write_text('\n'.join(lines), encoding='utf-8')
old = pathlib.Path('js/constraints-pending.js').stat().st_size
print(f'{len(kept)} approved constraints written to js/constraints-live.js')
print(f'{old//1024} KB -> {p.stat().st_size//1024} KB')
