#!/usr/bin/env python3
"""Generate functions/_sitemap-lastmod.js from real git history.

The sitemap carried no lastmod at all, and lastmod is the main signal Google
uses to decide what to re-crawl. The index reading of 20 September 2026 showed
why that matters here: 277 of 757 pages had never been crawled and 231 had not
been seen since July.

The date has to be honest or Google ignores it. The last commit that touched a
file is the wrong answer on this repo: a cache-bust pass rewrites the ?v=N query
string on 2,000 pages at once without changing a word anyone reads, and stamping
all of them as freshly modified is exactly the noise that gets lastmod
discounted. So walk each file's history newest first and take the first commit
whose diff for that file changes something other than an asset version.
"""
import json, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIP = {'node_modules', '.git', 'tmp', 'marketing', 'scripts', 'admin', 'seo-snapshots'}
OUT = ROOT / 'functions' / '_sitemap-lastmod.js'
MAX_WALK = 12  # commits to look back before giving up and taking the newest

ROBOTS = re.compile(r'<meta[^>]*name="robots"[^>]*content="([^"]*)"', re.I)
# A line that only moves an asset version, e.g. style.css?v=23 -> ?v=24
ONLY_VERSION = re.compile(r'^[+-].*\?v=\d+')


def git(*args):
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True).stdout


def meaningful_date(rel):
    """Newest commit touching this file whose change is more than a ?v= bump."""
    log = git('log', '--format=%H %cs', '--', rel).strip().splitlines()
    if not log:
        return None
    for line in log[:MAX_WALK]:
        sha, date = line.split(' ', 1)
        patch = git('show', '--format=', '--unified=0', sha, '--', rel)
        body = [l for l in patch.splitlines()
                if l.startswith(('+', '-')) and not l.startswith(('+++', '---'))]
        if not body:
            continue
        if all(ONLY_VERSION.match(l) for l in body):
            continue          # cache-bust only, keep walking back
        return date
    return log[0].split(' ', 1)[1]


def main():
    pages = []
    for p in sorted(ROOT.rglob('index.html')):
        if any(s in p.parts for s in SKIP):
            continue
        html = p.read_text(encoding='utf-8', errors='ignore')
        if any('noindex' in v.lower() for v in ROBOTS.findall(html)):
            continue
        d = str(p.parent.relative_to(ROOT)).replace('\\', '/')
        pages.append(('/' if d == '.' else f'/{d}/', str(p.relative_to(ROOT))))

    if not pages:
        sys.exit('Found no indexable page. A generator that writes an empty map and reports '
                 'success has checked nothing, so this stops instead.')

    out, bumped_only = {}, 0
    for i, (url, rel) in enumerate(pages, 1):
        d = meaningful_date(rel)
        if d:
            out[url] = d
        newest = git('log', '-1', '--format=%cs', '--', rel).strip()
        if newest and d and newest != d:
            bumped_only += 1
        if i % 150 == 0:
            print(f'  {i}/{len(pages)}')

    body = ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(out.items()))
    OUT.write_text(
        '// Generated by scripts/build-sitemap-lastmod.py. Do not edit by hand.\n'
        '//\n'
        '// Last date each indexable page changed in a way a reader would notice.\n'
        '// Commits that only move an asset ?v=N are walked past on purpose: a\n'
        '// cache-bust pass rewrites 2,000 pages without changing a word, and\n'
        '// stamping them all as fresh is what gets lastmod discounted.\n'
        f'export const LASTMOD = {{\n{body},\n}};\n', encoding='utf-8')

    # Always report the counts. A generator that says "done" over zero pages
    # reads exactly like one that worked.
    print(f'{len(out)} indexable pages dated, out of {len(pages)} scanned')
    print(f'{bumped_only} would have been stamped today by a naive "last commit" read')
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
